### PR TITLE
Adding support for multiple return values in the nodeback

### PR DESCRIPTION
**Pull request by tomayac**

### CODE REVIEW

**Comment by tomayac** [comment]
Unsure about the failed tests, it's working fine locally with the nodebacks I tested this with. I'm not familiar with Travis, and due to time constraints can't look into it right now. Do you see what's wrong on your side? Thanks!

**Comment by vinniegarcia** [comment]
Thanks @tomayac! I actually wrote tests for our proposed modification last night. I'll merge your changes with mine and reconcile until the tests pass :)

**Comment by vinniegarcia** [comment]
Published `proposal@1.2.0` with support for multiple returned parameters in a callback.

**Comment by tomayac** [comment]
Perfect, thanks :-D

**Pull request merged**
