### PR TITLE
Added support for multiple return values in the nodeback

### PR DESCRIPTION
**Pull request by tomayac**
Now supports nodebacks of the style callback(err, data_1, …, data_n).

### CODE REVIEW

**Comment by tomayac** [comment]
Pardon, realizing now that this pull request would violate the spec, as `onFulfilled` takes only _one_ argument, not several: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then. Closing the pull request.

**Comment by vinniegarcia** [comment]
I'm not opposed to the idea of multiple return values/args even if it does violate the spec. For example, `child_process.exec` returns `stdout` and `stderr`, which is valuable on certain calls even when successful (for example, `curl` calls write to both). Maybe return the args as an array if multiples are present?

**Comment by vinniegarcia** [comment]
Maybe a change like this would work: 

``` javascript
const denode = (resolve, reject) => (err, ...args) => (err) ? reject(err) : (args.length > 1 ? resolve([...args]) : resolve(args));
```

This might be less than optimal though if one has to call `Array.isArray` in `.then()` to check for argument size/type.

**Comment by tomayac** [comment]
I was thinking of something like this right now. A `Promise` _must_ be a `Promise`, no matter what, so _one_ return value it is. I'm in favor of your solution! You don't want to lose out on the other return values after the "Promisification", so I can happily live with `onFulfilled` to return an array at times.

**Pull request closed without merging**
